In [1]:
import numpy as np

In [2]:
def michalewicz(x, m=10):
    return -sum([np.sin(v) * np.sin(((i+1)*(v**2))/np.pi)**(2*m) for i, v in enumerate(x)])

In [3]:
michalewicz([2.2, 1.57])

-1.801140718473825

In [4]:
POP_SIZE = 10
DIM = 2

In [6]:
population = np.random.uniform(low=0, high=4, size=(POP_SIZE, DIM))
collection = [michalewicz(ind) for ind in population]

In [7]:
population

array([[2.85543149, 0.06278015],
       [2.36497366, 1.22576653],
       [1.42359771, 3.01980414],
       [0.91094965, 0.85942644],
       [1.02612513, 3.38921245],
       [1.76033815, 0.09561912],
       [3.27736487, 1.43978572],
       [3.58273847, 3.86425653],
       [1.11934809, 2.10972329],
       [0.58386025, 0.21724923]])

In [8]:
collection # 목적함수 값

[-5.784247226982215e-07,
 -0.4669350570412576,
 -3.775701409059554e-05,
 -1.0065845729445483e-07,
 0.011205914640695794,
 -0.02604978145503406,
 -0.52422760368754,
 0.006318914610238862,
 -5.510501216113062e-09,
 -2.71428041998087e-20]

In [9]:
def selection(f, population, k):
    
    collection = [f(ind) for ind in population]
    pool = np.argsort(collection)
    
    return [population[p] for i, p in enumerate(pool) if i < k]

In [10]:
new_population = selection(michalewicz, population, 4)
new_population

[array([3.27736487, 1.43978572]),
 array([2.36497366, 1.22576653]),
 array([1.76033815, 0.09561912]),
 array([1.42359771, 3.01980414])]

In [17]:
def parents(population):
    parent = list()
    
    for _ in range(POP_SIZE):
        idx = np.random.randint(low=0, high=len(population), size=len(population[0]))
        parent.append([population[idx[0]], population[idx[1]]])
        
    return parent

In [18]:
parent = parents(new_population)
parent

[[array([2.36497366, 1.22576653]), array([1.42359771, 3.01980414])],
 [array([1.42359771, 3.01980414]), array([3.27736487, 1.43978572])],
 [array([1.76033815, 0.09561912]), array([1.76033815, 0.09561912])],
 [array([1.42359771, 3.01980414]), array([1.76033815, 0.09561912])],
 [array([1.76033815, 0.09561912]), array([3.27736487, 1.43978572])],
 [array([1.76033815, 0.09561912]), array([2.36497366, 1.22576653])],
 [array([3.27736487, 1.43978572]), array([3.27736487, 1.43978572])],
 [array([1.76033815, 0.09561912]), array([2.36497366, 1.22576653])],
 [array([2.36497366, 1.22576653]), array([3.27736487, 1.43978572])],
 [array([1.42359771, 3.01980414]), array([1.76033815, 0.09561912])]]

In [19]:
def crossover(parents, lambda_=0.5):
    return [(1.-lambda_)*p[0] + lambda_*p[1] for p in parents]

In [20]:
child = crossover(parent)
child

[array([1.89428568, 2.12278533]),
 array([2.35048129, 2.22979493]),
 array([1.76033815, 0.09561912]),
 array([1.59196793, 1.55771163]),
 array([2.51885151, 0.76770242]),
 array([2.0626559 , 0.66069282]),
 array([3.27736487, 1.43978572]),
 array([2.0626559 , 0.66069282]),
 array([2.82116926, 1.33277612]),
 array([1.59196793, 1.55771163])]

In [21]:
def mutation(child, sigma):
    return child + np.random.normal(loc=0, scale=sigma, size=(len(child), len(child[0])))

In [22]:
mutation(child, 1./len(child))

array([[1.80874348, 2.18987804],
       [2.41443354, 2.49388738],
       [1.737488  , 0.24131443],
       [1.58473878, 1.55274208],
       [2.57354204, 0.69528706],
       [2.23737371, 0.64140893],
       [3.38009928, 1.51705609],
       [2.29603584, 0.55118243],
       [2.91203259, 1.49929717],
       [1.56633555, 1.47124716]])

In [23]:
def genetic_algorithm(f, pop_size, dim, k, maxiter=100):
    
    population = np.random.uniform(low=0, high=4, size=(pop_size, dim))
    collection = [f(ind) for ind in population]
    
    flag = True
    i = 1
    
    while flag:
        
        population = selection(f, population, k)
        parent = parents(population)
        child = crossover(parent)
        
        population = mutation(child, 1./len(child))
        collection = [f(ind) for ind in population]
        
        if i > maxiter:
            break
        
        i += 1
        
    pool = np.argsort(collection)
    
    return collection[pool[0]], population[pool[0]]

In [27]:
POP_SIZE = 50
DIM = 2
k = 10

genetic_algorithm(michalewicz, POP_SIZE, DIM, k=10)

(-1.8009866002581045, array([2.19887172, 1.57193835]))