In [2]:
import numpy as np

In [3]:
import tensorflow as tf

In [4]:
print(tf.__version__)

2.7.0


In [5]:
import torch

In [6]:
print(torch.__version__)

1.10.1


### List와 비교

In [7]:
a = np.array([1, 2, 3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


In [8]:
#List와 ndarray 비교

L = [1, 2, 3]
A = np.array([1, 2, 3])
print(L)
print(A)

[1, 2, 3]
[1 2 3]


In [9]:
A

array([1, 2, 3])

In [10]:
for item in L:
    print(item)

1
2
3


In [11]:
for item in A:
    print(item)

1
2
3


In [12]:
L.append(4)
print(L)

[1, 2, 3, 4]


In [13]:
A = np.append(A, 4)
print(A)

[1 2 3 4]


In [14]:
L = L + [5]
print(L)

[1, 2, 3, 4, 5]


In [15]:
A = A + np.array([5])
print(A)

[6 7 8 9]


In [18]:
#list의 원소 2배로 만들기

L = [1, 2, 3]
L2 = []

for item in L:
    L2.append(item*2)
print(L2)

[2, 4, 6]


In [19]:
A = np.array(L)
A2 = A*2
print(A2)

[2 4 6]


In [20]:
L*2

[1, 2, 3, 1, 2, 3]

### 배열 생성

In [22]:
a = np.array([1, 2, 3])
print(a)
print(type(a), a.ndim, a.shape, a.dtype)

[1 2 3]
<class 'numpy.ndarray'> 1 (3,) int32


In [23]:
b = np.asarray(a) #asarray를 사용하면 복사x
print(b)

[1 2 3]


In [24]:
b[0] = 9
print(a)
print(b)

[9 2 3]
[9 2 3]


In [25]:
c = np.array(a)
print(c)

[9 2 3]


In [26]:
c[0] = 1
print(a)
print(b)
print(c)

[9 2 3]
[9 2 3]
[1 2 3]


In [29]:
a = np.zeros((3, 4))
print(a)
print(a.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


In [30]:
b = np.ones((5, 2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [31]:
c = np.full((2,3), 4)
print(c)

[[4 4 4]
 [4 4 4]]


In [33]:
d = np.empty((3,3))
print(d)

[[0.0000e+000 0.0000e+000 0.0000e+000]
 [0.0000e+000 0.0000e+000 1.7134e-320]
 [0.0000e+000 0.0000e+000 0.0000e+000]]


In [34]:
e = np.zeros_like(a)
f = np.ones_like(a)
g = np.full_like(a, 2)
h = np.empty_like(a)
print(e)
print(f)
print(g)
print(h)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[1.01895978e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [1.89146896e-307 1.16095484e-028 3.74168445e+233 3.10573437e-115]
 [3.77075632e+233 4.06683016e-144 2.91237123e+257 4.71294503e+257]]


In [35]:
# 단위행렬 생성
i = np.eye(3)
j = np.identity(3)
print(i)
print(j)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
k = np.arange(10)
print(k)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
#uniform distribution
l = np.random.rand(2,2)
print(l)

[[0.56086584 0.93874212]
 [0.31285753 0.22429877]]


In [39]:
# standard normal distribution
m = np.random.randn(2, 2)
print(m)

[[-0.70333498  1.6262337 ]
 [-0.08753991  1.5252653 ]]


### 배열 dtype

In [40]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3], dtype=np.float64)
c = np.array([1, 2, 3], dtype=np.int32)
print(a.dtype, b.dtype, c.dtype)

int32 float64 int32


In [41]:
d = np.array([1, 2, 3], dtype='i1')
e = np.array([1, 2, 3], dtype='i2')
f = np.array([1, 2, 3], dtype='i4')
g = np.array([1, 2, 3], dtype='i8')
print(d.dtype, e.dtype, f.dtype, g.dtype)

int8 int16 int32 int64


In [43]:
d = np.array([1, 2, 3], dtype='u1')
e = np.array([1, 2, 3], dtype='u2')
f = np.array([1, 2, 3], dtype='u4')
g = np.array([1, 2, 3], dtype='u8')
print(d.dtype, e.dtype, f.dtype, g.dtype)

uint8 uint16 uint32 uint64


In [48]:
h = np.array([1, 2, 3], dtype='f2')
i = np.array([1, 2, 3], dtype='f4')
j = np.array([1, 2, 3], dtype='f8')
print(h.dtype, i.dtype, j.dtype)

float16 float32 float64


In [50]:
i = np.array([1, 2, 3], dtype='f')
j = np.array([1, 2, 3], dtype='d')
print(h.dtype, i.dtype, j.dtype)

float16 float32 float64


In [51]:
i = i.astype(np.int32)
print(i.dtype)

int32


In [52]:
j = j.astype(i.dtype)
print(j.dtype)

int32


### 배열 indexing&slicing

In [53]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [54]:
#indexing
print(a[5])

5


In [55]:
#slicing
print(a[5:8])

[5 6 7]


In [56]:
a[-1]

9

In [57]:
print(a[7:-1])

[7 8]


In [58]:
a[5:8] = 10
print(a)

[ 0  1  2  3  4 10 10 10  8  9]


### indexing과 slicing 차이
- indexing을 사용하면 항상 차원이 감소, 반면에 slicing을 하면 차원이 유지

In [59]:
b = np.arange(1, 13)
print(b)
print(b.shape)
print(b.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
1


In [60]:
indexing = b[1]
slicing = b[1:2]
print(indexing, indexing.shape, indexing.ndim)
print(slicing, slicing.shape, slicing.ndim)

2 () 0
[2] (1,) 1


In [62]:
b = b.reshape(3, 4)
print(b)
print(b.shape)
print(b.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2


In [63]:
r1 = b[1, :]
r2 = b[1:2, :]
print(r1, r1.shape, r1.ndim)
print(r2, r2.shape, r2.ndim)

[5 6 7 8] (4,) 1
[[5 6 7 8]] (1, 4) 2


### slicing example

In [65]:
c = np.arange(24).reshape(2, 3, 4)
print(c)
print(c.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [66]:
print(c[:,:,:1])
print(c[...,:1])

[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]
[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]


In [67]:
print(c[0:1])
print(c[0::-1])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


### boolean indexing

In [68]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [69]:
bool_idx = (c > 10)
print(bool_idx)

[[[False False False False]
  [False False False False]
  [False False False  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


In [70]:
print(c[bool_idx])

[11 12 13 14 15 16 17 18 19 20 21 22 23]


In [71]:
c[c>10] = -1
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 -1]]

 [[-1 -1 -1 -1]
  [-1 -1 -1 -1]
  [-1 -1 -1 -1]]]


### fancy indexing

In [75]:
d = np.arange(8).reshape(8,-1)
print(d, d.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] (8, 1)


In [76]:
d = np.hstack((d, d, d, d))
print(d, d.shape)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]] (8, 4)


In [77]:
print(d[[3, 5, 7, 0]])

[[3 3 3 3]
 [5 5 5 5]
 [7 7 7 7]
 [0 0 0 0]]


In [78]:
print(d[[-3,-5,-7]])

[[5 5 5 5]
 [3 3 3 3]
 [1 1 1 1]]


In [79]:
e = np.arange(32).reshape(8,4)
print(e, e.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] (8, 4)


In [80]:
print(e[[1,5,7,2]])

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]


In [83]:
print(e[[1,5,7,2], [0,3,1,2]])

[ 4 23 29 10]


In [85]:
print(e[[1,5,7,2]][:, [0,3,1,2]])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


### Transpose

In [88]:
f = np.arange(16).reshape(2,2,4)
print(f, f.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4)


In [93]:
print(f.transpose(1,0,2), f.transpose(1,0,2).shape)

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]] (2, 2, 4)


In [94]:
print(f.transpose(2, 1, 0), f.transpose(2, 1, 0).shape)

[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]] (4, 2, 2)


### numpy 연산

In [3]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [4]:
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [5]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [6]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [7]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [8]:
# 행렬의 곱
print(x @ y)
print(np.matmul(x, y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [10]:
z = np.arange(1, 11).reshape(2,5)
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
print(np.sum(z))

55


In [13]:
sum1 = np.sum(z, axis=0)
sum2 = np.sum(z, axis=1)
sum3 = np.sum(z, axis=-1)
print(sum1, sum1.shape)
print(sum2, sum2.shape)
print(sum3, sum3.shape)

[ 7  9 11 13 15] (5,)
[15 40] (2,)
[15 40] (2,)


- 축(axis)은 각 배열의 차원에 해당하는 index입니다.  
- axis=0에 대하여 sum을 하라는 것은 0번 축 혹은 차원이 없어지는 방향으로 원소들을 모두 더하라는 이야기입니다.  
- 위의 예에서 sum1의 경우 열의 합, sum2의 경우 행의 합을 구하는 연산을 하라는 의미

In [14]:
print(z[0,:]+z[1,:])

[ 7  9 11 13 15]


In [15]:
print(z[:,0]+z[:,1]+z[:,2]+z[:,3]+z[:,4])

[15 40]


### Broadcasting
- broadcasting은 numpy가 산술 연산을 시행할 때 다른 모양의 배열로 작업할 수 있게 해주는 강력한 메커니즘
- 더 작은 배열과 더 큰 배열이 있을 때 더 작은 배열을 여러 번 사용하여 더 큰 배열에서 어떠한 연산을 수행
- 예) 행렬의 각 행에 상수 벡터를 추가하는 경우

In [16]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
y = np.array([1,0,2])
print(x, x.shape)
print(y, y.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)
[1 0 2] (3,)


In [17]:
z = x + y
print(z, z.shape)

[[ 2  2  5]
 [ 5  5  8]
 [ 8  8 11]
 [11 11 14]] (4, 3)


In [18]:
x = np.array([1, 2, 3]).reshape(1, 3)
y = np.array([4, 5]).reshape(1, 2)
print(x, x.shape)
print(y, y.shape)

[[1 2 3]] (1, 3)
[[4 5]] (1, 2)


In [19]:
print(x + y)
# 브로드캐스팅 조건에 맞지 않음

ValueError: operands could not be broadcast together with shapes (1,3) (1,2) 

In [26]:
y = y.transpose(1, 0)
print(y, y.shape)

[[4]
 [5]] (2, 1)


In [27]:
print(x + y)

[[5 6 7]
 [6 7 8]]


### shape 변경

In [32]:
a = np.arange(24).reshape(2, 3, 4)
print(a, a.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] (2, 3, 4)


In [33]:
a = a.reshape(4, -1)
print(a, a.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] (4, 6)


In [34]:
a = a[..., np.newaxis]
print(a, a.shape)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]
  [16]
  [17]]

 [[18]
  [19]
  [20]
  [21]
  [22]
  [23]]] (4, 6, 1)


In [39]:
a = a.reshape(4, 6)
a = np.expand_dims(a, axis=0)
print(a, a.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]] (1, 4, 6)


In [40]:
b = a.copy()
print(b, b.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]] (1, 4, 6)


In [41]:
c = np.concatenate((a,b), axis=-1)
print(c, c.shape)

[[[ 0  1  2  3  4  5  0  1  2  3  4  5]
  [ 6  7  8  9 10 11  6  7  8  9 10 11]
  [12 13 14 15 16 17 12 13 14 15 16 17]
  [18 19 20 21 22 23 18 19 20 21 22 23]]] (1, 4, 12)


In [42]:
c = np.concatenate((a,b), axis=0)
print(c, c.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]] (2, 4, 6)


In [43]:
# concat은 차원이 유지되지만 stack은 차원이 추가됨
d = np.stack((a,b), axis=-1)
print(d, d.shape)

[[[[ 0  0]
   [ 1  1]
   [ 2  2]
   [ 3  3]
   [ 4  4]
   [ 5  5]]

  [[ 6  6]
   [ 7  7]
   [ 8  8]
   [ 9  9]
   [10 10]
   [11 11]]

  [[12 12]
   [13 13]
   [14 14]
   [15 15]
   [16 16]
   [17 17]]

  [[18 18]
   [19 19]
   [20 20]
   [21 21]
   [22 22]
   [23 23]]]] (1, 4, 6, 2)


In [44]:
d = np.stack((a,b), axis=0)
print(d, d.shape)

[[[[ 0  1  2  3  4  5]
   [ 6  7  8  9 10 11]
   [12 13 14 15 16 17]
   [18 19 20 21 22 23]]]


 [[[ 0  1  2  3  4  5]
   [ 6  7  8  9 10 11]
   [12 13 14 15 16 17]
   [18 19 20 21 22 23]]]] (2, 1, 4, 6)
