In [1]:
%tensorflow_version 2.x
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


# 1-1: Affine Functions with 1 Feature

## Affine Function

In [2]:
from tensorflow.keras.layers import Dense

In [26]:
x = tf.constant([[10.]]) # input(->matrix)

dense = Dense(units=1, activation='linear') # affine function
y_tf = dense(x) # forward propagation + prams initailization

W, B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B

print('----- Input/Weight/Bias-----')
print(f'x: {x.shape}\n {x.numpy()}')
print(f'W: {W.shape}\n {W}')
print(f'B: {B.shape}\n {B}')

print('----- Outputs -----')
print(f'y(Tensorflow): {y_tf.shape}\n {y_tf.numpy()}')
print(f'y(Maunal): {y_man.shape}\n {y_man.numpy()}')

----- Input/Weight/Bias-----
x: (1, 1)
 [[10.]]
W: (1, 1)
 [[1.208079]]
B: (1,)
 [0.]
----- Outputs -----
y(Tensorflow): (1, 1)
 [[12.08079]]
y(Maunal): (1, 1)
 [[12.08079]]


## Params Initailization

In [17]:
from tensorflow.keras.initializers import Constant

In [21]:
x = tf.constant([[10.]])

# weight/bias setting
w, b = tf.constant(10.), tf.constant(20.)
w_init, b_init = Constant(w), Constant(b)

# affine function
dense = Dense(units=1, activation='linear', kernel_initializer=w_init, bias_initializer=b_init)
y_tf = dense(x)

W, B = dense.get_weights()

print(f'W: {W.shape}\n{W}')
print(f'W: {B.shape}\n{B}')
print(y_tf)

W: (1, 1)
[[10.]]
W: (1,)
[20.]
tf.Tensor([[120.]], shape=(1, 1), dtype=float32)


# 1-2: Affine Functions with n Features

## Affine Functions with n Features

In [27]:
x = tf.random.uniform(shape=(1, 10), minval=0, maxval=10)
dense = Dense(units=1)

y_tf = dense(x)

W, B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B

print('----- Input/Weight/Bias-----')
print(f'x: {x.shape}\n {x.numpy()}')
print(f'W: {W.shape}\n {W}')
print(f'B: {B.shape}\n {B}')

print('----- Outputs -----')
print(f'y(Tensorflow): {y_tf.shape}\n {y_tf.numpy()}')
print(f'y(Manual): {y_man.shape}\n {y_man.numpy()}')

----- Input/Weight/Bias-----
x: (1, 10)
 [[1.7806864e+00 7.6199245e+00 8.5536423e+00 2.8632236e+00 1.7231500e+00
  4.1449642e+00 3.2004309e+00 8.4408779e+00 4.2498112e-03 8.7588177e+00]]
W: (10, 1)
 [[-0.35802588]
 [-0.1088106 ]
 [ 0.21715128]
 [-0.6479246 ]
 [-0.6718304 ]
 [-0.5118372 ]
 [ 0.34941155]
 [ 0.3509602 ]
 [ 0.17161036]
 [ 0.6180374 ]]
B: (1,)
 [0.]
----- Outputs -----
y(Tensorflow): (1, 1)
 [[4.751096]]
y(Manual): (1, 1)
 [[4.751096]]


# 1-3: Activation Function

## Activation Layers

In [29]:
from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

In [38]:
x = tf.random.normal(shape=(1, 5))

# activation function
sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

# forward propagation(Tensorflow)
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

# forward propagation(manual)
y_sigmoid_man = 1 / (1 + exp(-x))
y_tanh_man = (exp(x)-exp(-x)) / (exp(x)+exp(-x))
y_relu_man = maximum(x, 0)

print(f'x: {x.shape}\n {x.numpy()}\n')
print(f'Sigmoid(Tensorflow): {y_sigmoid_tf.shape}\n {y_sigmoid_tf.numpy()}')
print(f'Sigmoid(manual): {y_sigmoid_man.shape}\n {y_sigmoid_man.numpy()}\n')

print(f'tanh(Tensorflow): {y_tanh_tf.shape}\n {y_tanh_tf.numpy()}')
print(f'tanh(manual): {y_tanh_man.shape}\n {y_tanh_man.numpy()}\n')

print(f'relu(Tensorflow): {y_relu_tf.shape}\n {y_relu_tf.numpy()}')
print(f'relu(manual): {y_relu_man.shape}\n {y_relu_man.numpy()}\n')

x: (1, 5)
 [[-0.7429203  -0.58472943  0.6063365   1.0477896   1.6943064 ]]

Sigmoid(Tensorflow): (1, 5)
 [[0.32236588 0.35784507 0.6471047  0.74035025 0.8447896 ]]
Sigmoid(manual): (1, 5)
 [[0.32236588 0.35784507 0.6471047  0.74035025 0.8447896 ]]

tanh(Tensorflow): (1, 5)
 [[-0.6309063  -0.5260944   0.5415431   0.78094554  0.9346935 ]]
tanh(manual): (1, 5)
 [[-0.63090634 -0.52609444  0.54154307  0.78094554  0.93469346]]

relu(Tensorflow): (1, 5)
 [[0.        0.        0.6063365 1.0477896 1.6943064]]
relu(manual): (1, 5)
 [[0.        0.        0.6063365 1.0477896 1.6943064]]



## Activation in Dense Layer

In [43]:
x = tf.random.normal(shape=(1, 5))

# artificial neurons
dense_sigmoid = Dense(units=1, activation='sigmoid')
dense_tanh = Dense(units=1, activation='tanh')
dense_relu = Dense(units=1, activation='relu')

# forward propagation(Tf)
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

print(f'AN with Sigmoid: {y_sigmoid.shape}, {y_sigmoid}')
print(f'AN with Tanh: {y_tanh.shape}, {y_tanh}')
print(f'AN with ReLU: {y_relu.shape}, {y_relu}')

# forward propagation(manual)
print('\n------\n')

W, B = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x, W) + B
a = 1 / (1 + exp(-z))

print(f'Activation value(Tensorflow): {y_sigmoid.shape}, {y_sigmoid}')
print(f'Activation value(manual): {a.shape}, {a}')

AN with Sigmoid: (1, 1), [[0.47490844]]
AN with Tanh: (1, 1), [[-0.3541515]]
AN with ReLU: (1, 1), [[0.45406222]]

------

Activation value(Tensorflow): (1, 1), [[0.47490844]]
Activation value(manual): (1, 1), [[0.47490844]]


# 1-4 Artificial Neurons

## Artificial Neurons

In [46]:
activation = 'sigmoid'
# activation = 'tanh'
# activation = 'relu'

x = tf.random.uniform(shape=(1, 10))
dense = Dense(units=1, activation=activation) # affine + activation

y_tf = dense(x)
W, B = dense.get_weights()

# calculate activation value manually
y_man = tf.linalg.matmul(x, W) + B
if activation == 'sigmoid':
  y_man = 1 / (1+exp(-y_man))
elif activation == 'tanh':
  y_man = (exp(y_man)-exp(-y_man)) / (exp(y_man)+exp(-y_man))
elif activation == 'relu':
  y_man = maximum(x, 0)

print(f'Activation: ', activation)
print(f'y_tf: {y_tf.shape}, {y_tf.numpy()}')
print(f'y_man: {y_man.shape}, {y_man.numpy()}')

Activation:  sigmoid
y_tf: (1, 1), [[0.41827446]]
y_man: (1, 1), [[0.41827446]]


# 1-5 Minibatches

## Shapes of Dense Layers

In [48]:
N, n_feature = 8, 10
x = tf.random.normal(shape=(N, n_feature)) # generate minibatch

dense = Dense(units=1, activation='relu') # AN
y = dense(x) # forward propagation

W,B = dense.get_weights()

print('Shape of x: ', x.shape)
print('Shape of W: ', W.shape)
print('Shape of B: ', B.shape)

Shape of x:  (8, 10)
Shape of W:  (10, 1)
Shape of B:  (1,)


## Output Calculations

In [51]:
N, n_feature = 8, 10
x = tf.random.normal(shape=(N, n_feature)) # generate minibatch

dense = Dense(units=1, activation='sigmoid') # AN
y_tf = dense(x) # forward propagation(tf)

W, B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B # forward propagation(manual)
y_man = 1 / (1+exp(-y_man))

print('Output(Tensorflow):\n', y_tf.numpy())
print('Output(manual):\n', y_man.numpy())

Output(Tensorflow):
 [[0.84246224]
 [0.13931608]
 [0.32082403]
 [0.5377062 ]
 [0.39307562]
 [0.28093055]
 [0.46097657]
 [0.49327222]]
Output(manual):
 [[0.84246224]
 [0.13931608]
 [0.32082403]
 [0.5377062 ]
 [0.39307562]
 [0.28093055]
 [0.46097657]
 [0.49327222]]
