In [1]:
import numpy as np

In [2]:
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [3]:
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [4]:
a1.dtype

dtype('int32')

In [5]:
a2.dtype

dtype('float64')

In [6]:
np.array([0.5, 2, 0.01, 8])

array([0.5 , 2.  , 0.01, 8.  ])

In [7]:
np.array([[1,2,3,], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.arange(12).reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
b1 = np.arange(12).reshape(4, 3)
b1.shape

(4, 3)

In [13]:
b2 = np.arange(5)
b2.shape

(5,)

In [14]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.array(['1.5', '0.62', '2', '3.14', '3.141592'])

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [23]:
str_a1 = np.array(['1.567', '0.123', '5.123', '9', '8'])
num_a1 = str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [24]:
str_a1.dtype

dtype('<U5')

In [25]:
num_a1.dtype

dtype('float64')

In [27]:
num_f1 = np.array([10, 21, 0.549, 4.75, 5.98])
num_i1 = num_f1.astype(int)
num_i1

array([10, 21,  0,  4,  5])

In [28]:
np.random.rand(2, 3)

array([[0.54112074, 0.48452528, 0.40999365],
       [0.01015291, 0.84091158, 0.7200257 ]])

In [29]:
np.random.rand()

0.3097054750089612

In [30]:
np.random.rand(2, 3, 4)

array([[[0.12966399, 0.86872675, 0.64216253, 0.41710627],
        [0.21901473, 0.3499496 , 0.49036707, 0.68565815],
        [0.72704271, 0.16304094, 0.93366075, 0.73352166]],

       [[0.18617198, 0.82022904, 0.31985434, 0.23669991],
        [0.83783302, 0.29457279, 0.40980466, 0.57333895],
        [0.37953051, 0.77302948, 0.31074458, 0.53426949]]])

In [31]:
np.random.randint(10, size=(3, 4))

array([[2, 5, 4, 1],
       [1, 3, 6, 6],
       [2, 8, 4, 6]])

In [32]:
np.random.randint(1, 30)

10

In [33]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [34]:
[arr3.sum(), arr3.mean()]

[10, 2.0]

In [36]:
[arr3.std(), arr3.var()]

[1.4142135623730951, 2.0]

In [37]:
[arr3.min(), arr3.max()]

[0, 4]

In [38]:
arr4 = np.arange(1, 5)
arr4

array([1, 2, 3, 4])

In [39]:
arr4.cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [40]:
arr4.cumprod()

array([ 1,  2,  6, 24], dtype=int32)

In [41]:
A = np.array([0, 1, 2, 3]).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [42]:
B = np.array([3, 2, 1, 0]).reshape(2, 2)
B

array([[3, 2],
       [1, 0]])

In [43]:
A.dot(B)

array([[1, 0],
       [9, 4]])

In [44]:
np.dot(A, B)

array([[1, 0],
       [9, 4]])

In [45]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [46]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [47]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [48]:
np.linalg.det(A)

-2.0

In [49]:
a1 = np.array([0, 10, 20, 30, 40, 50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [50]:
a1[0]

0

In [51]:
a1[[1, 3, 4]]

array([10, 30, 40])

In [52]:
a2 = np.arange(10, 100, 10).reshape(3, 3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [57]:
a2[2, 2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [58]:
a2[1]

array([40, 50, 60])

In [59]:
a2[1] = np.array([45, 55, 65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [60]:
a2[[0, 2], [0, 1]]

array([10, 80])

In [61]:
a = np.array([1, 2, 3, 4, 5, 6])
a[a>3]

array([4, 5, 6])

In [62]:
a[(a % 2) == 0]

array([2, 4, 6])

In [63]:
b1 = np.array([0, 10, 20, 30, 40, 50])
b1[1:4]

array([10, 20, 30])

In [64]:
b1[:3]

array([ 0, 10, 20])

In [66]:
b1[2:]

array([20, 30, 40, 50])

In [67]:
b1[2:5] = np.array([25, 35, 45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [68]:
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

In [69]:
b2 = np.arange(10, 100, 10).reshape(3, 3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [70]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [72]:
b2[0:2, 1:3] = np.array([[25, 35], [55, 65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])

In [73]:
import pandas as pd

In [75]:
s1 = pd.Series([10, 20, 30, 40, 50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [76]:
s1.index
print(s1.index)

RangeIndex(start=0, stop=5, step=1)


In [77]:
s1.values

array([10, 20, 30, 40, 50], dtype=int64)

In [78]:
s2 = pd.Series(['a', 'b', 'c', 1, 2, 3])
s2

0    a
1    b
2    c
3    1
4    2
5    3
dtype: object

In [79]:
s3 = pd.Series([np.nan, 10, 30])
s3

0     NaN
1    10.0
2    30.0
dtype: float64

In [80]:
index_date = ['2021-12-06', '2021-12-07', '2021-12-08', '2021-12-09']
s4 = pd.Series([200, 195, np.nan, 205], index = index_date)
s4

2021-12-06    200.0
2021-12-07    195.0
2021-12-08      NaN
2021-12-09    205.0
dtype: float64

In [81]:
s5 = pd.Series({'국어':100, '영어':80, '수학':50})
s5

국어    100
영어     80
수학     50
dtype: int64

In [82]:
pd.date_range(start='2022-01-01', end='2022-01-07')

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07'],
              dtype='datetime64[ns]', freq='D')

In [84]:
pd.date_range(start='2022-01-01', periods = 7)

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07'],
              dtype='datetime64[ns]', freq='D')

In [86]:
pd.date_range(start='2021-12-06', periods=4, freq='W-MON')

DatetimeIndex(['2021-12-06', '2021-12-13', '2021-12-20', '2021-12-27'], dtype='datetime64[ns]', freq='W-MON')

In [87]:
pd.date_range(start='2021-11-22', periods=14, freq='BH')

DatetimeIndex(['2021-11-22 09:00:00', '2021-11-22 10:00:00',
               '2021-11-22 11:00:00', '2021-11-22 12:00:00',
               '2021-11-22 13:00:00', '2021-11-22 14:00:00',
               '2021-11-22 15:00:00', '2021-11-22 16:00:00',
               '2021-11-23 09:00:00', '2021-11-23 10:00:00',
               '2021-11-23 11:00:00', '2021-11-23 12:00:00',
               '2021-11-23 13:00:00', '2021-11-23 14:00:00'],
              dtype='datetime64[ns]', freq='BH')

In [88]:
pd.DataFrame([[1,2,3], [4, 5,6], [7,8,9]])

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [90]:
data_list = np.array([[10,20,30], [40,50,60], [70,80,90]])
pd.DataFrame(data_list)

0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [91]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
index_date = pd.date_range('2021-12-06', periods=4)
columns_list = ['A', 'B', 'C']
pd.DataFrame(data, index=index_date, columns=columns_list)

A   B   C
2021-12-06   1   2   3
2021-12-07   4   5   6
2021-12-08   7   8   9
2021-12-09  10  11  12

In [95]:
table_data = {'연도':[2015, 2016,2016,2017,2017],
              '지사':['한국','한국','미국','한국','미국'],
              '고객 수':[200, 250, 450, 300, 500]}
df = pd.DataFrame(table_data)
df

연도  지사  고객 수
0  2015  한국   200
1  2016  한국   250
2  2016  미국   450
3  2017  한국   300
4  2017  미국   500

In [96]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [97]:
df.columns

Index(['연도', '지사', '고객 수'], dtype='object')

In [98]:
df.values

array([[2015, '한국', 200],
       [2016, '한국', 250],
       [2016, '미국', 450],
       [2017, '한국', 300],
       [2017, '미국', 500]], dtype=object)

In [100]:
s3 = pd.Series([1, 2, 3, 4])
s4 = pd.Series([10, 20, 30, 40, 50])
s3 + s4

0    11.0
1    22.0
2    33.0
3    44.0
4     NaN
dtype: float64

In [101]:
table_data1 = {'A':[1, 2, 3, 4, 5],
               'B':[10, 20, 30, 40, 50],
               'C':[100,200,300,400,500]}
df1 = pd.DataFrame(table_data1)
df1

A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [102]:
table_data2 = {'A':[6, 7, 8],
               'B':[60, 70, 80],
               'C':[600, 700, 800]}

df2 = pd.DataFrame(table_data2)
df2

A   B    C
0  6  60  600
1  7  70  700
2  8  80  800

In [103]:
df1 + df2

A      B       C
0   7.0   70.0   700.0
1   9.0   90.0   900.0
2  11.0  110.0  1100.0
3   NaN    NaN     NaN
4   NaN    NaN     NaN

In [105]:
table_data3 = {'봄':  [256.5, 264.3, 215.9, 223.2, 312.8],
              '여름': [770.6, 567.5, 599.8, 387.1, 446.2],
              '가을': [363.5, 231.2, 293.1, 247.7, 381.6],
              '겨울': [139.3, 59.9, 76.9, 109.1, 108.1]}
columns_list = ['봄', '여름', '가을', '겨울']
index_list = ['2012', '2013', '2014', '2015', '2016']

df3 = pd.DataFrame(table_data3, columns = columns_list, index = index_list)
df3

봄     여름     가을     겨울
2012  256.5  770.6  363.5  139.3
2013  264.3  567.5  231.2   59.9
2014  215.9  599.8  293.1   76.9
2015  223.2  387.1  247.7  109.1
2016  312.8  446.2  381.6  108.1

In [106]:
df3.mean()

봄     254.54
여름    554.24
가을    303.42
겨울     98.66
dtype: float64

In [107]:
df3.std()

봄      38.628267
여름    148.888895
가을     67.358496
겨울     30.925523
dtype: float64

In [108]:
df3.mean(axis=1)

2012    382.475
2013    280.725
2014    296.425
2015    241.775
2016    312.175
dtype: float64

In [109]:
df3.std(axis=1)

2012    274.472128
2013    211.128782
2014    221.150739
2015    114.166760
2016    146.548658
dtype: float64

In [111]:
df3.describe()

봄          여름          가을          겨울
count    5.000000    5.000000    5.000000    5.000000
mean   254.540000  554.240000  303.420000   98.660000
std     38.628267  148.888895   67.358496   30.925523
min    215.900000  387.100000  231.200000   59.900000
25%    223.200000  446.200000  247.700000   76.900000
50%    256.500000  567.500000  293.100000  108.100000
75%    264.300000  599.800000  363.500000  109.100000
max    312.800000  770.600000  381.600000  139.300000

In [113]:
KTX_data = {'경부선 KTX': [39060, 39896, 42005, 43621, 41702, 41266, 32427],
            '호남선 KTX': [7313, 6967, 6873, 6626, 8675, 10622, 9228],
            '경전선 KTX': [3627, 4168, 4088, 4424, 4606, 4984, 5570],
            '전라선 KTX': [309, 1771, 1954, 2244, 3146, 3945, 5766],
            '동해선 KTX': [np.nan,np.nan, np.nan, np.nan, 2395, 3786, 6667]}
col_list = ['경부선 KTX','호남선 KTX','경전선 KTX','전라선 KTX','동해선 KTX']
index_list = ['2011', '2012', '2013', '2014', '2015', '2016', '2017']

df_KTX = pd.DataFrame(KTX_data, columns=col_list, index=index_list)
df_KTX

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0

In [114]:
df_KTX.index

Index(['2011', '2012', '2013', '2014', '2015', '2016', '2017'], dtype='object')

In [115]:
df_KTX.columns

Index(['경부선 KTX', '호남선 KTX', '경전선 KTX', '전라선 KTX', '동해선 KTX'], dtype='object')

In [116]:
df_KTX.values

array([[39060.,  7313.,  3627.,   309.,    nan],
       [39896.,  6967.,  4168.,  1771.,    nan],
       [42005.,  6873.,  4088.,  1954.,    nan],
       [43621.,  6626.,  4424.,  2244.,    nan],
       [41702.,  8675.,  4606.,  3146.,  2395.],
       [41266., 10622.,  4984.,  3945.,  3786.],
       [32427.,  9228.,  5570.,  5766.,  6667.]])

In [117]:
df_KTX.head()

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0

In [118]:
df_KTX.tail()

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0

In [120]:
df_KTX[1:2]

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2012    39896     6967     4168     1771      NaN

In [122]:
df_KTX[2:5]

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0

In [125]:
df_KTX.loc['2011']

경부선 KTX    39060.0
호남선 KTX     7313.0
경전선 KTX     3627.0
전라선 KTX      309.0
동해선 KTX        NaN
Name: 2011, dtype: float64

In [126]:
df_KTX.loc['2013':'2016']

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0

In [127]:
df_KTX['경부선 KTX']

2011    39060
2012    39896
2013    42005
2014    43621
2015    41702
2016    41266
2017    32427
Name: 경부선 KTX, dtype: int64

In [128]:
df_KTX['경부선 KTX']['2012':'2014']

2012    39896
2013    42005
2014    43621
Name: 경부선 KTX, dtype: int64

In [129]:
df_KTX['경부선 KTX'][2:5]

2013    42005
2014    43621
2015    41702
Name: 경부선 KTX, dtype: int64

In [130]:
df_KTX.loc['2016']['호남선 KTX']

10622.0

In [132]:
df_KTX.loc['2016', '호남선 KTX']

10622

In [133]:
df_KTX['호남선 KTX'].loc['2016']

10622

In [134]:
df_KTX.T

2011     2012     2013     2014     2015     2016     2017
경부선 KTX  39060.0  39896.0  42005.0  43621.0  41702.0  41266.0  32427.0
호남선 KTX   7313.0   6967.0   6873.0   6626.0   8675.0  10622.0   9228.0
경전선 KTX   3627.0   4168.0   4088.0   4424.0   4606.0   4984.0   5570.0
전라선 KTX    309.0   1771.0   1954.0   2244.0   3146.0   3945.0   5766.0
동해선 KTX      NaN      NaN      NaN      NaN   2395.0   3786.0   6667.0

In [135]:
df1 = pd.DataFrame({'Class1':[95,92,98,100],
                    'Class2':[91,93,97,99]})
df1

Class1  Class2
0      95      91
1      92      93
2      98      97
3     100      99

In [136]:
df2 = pd.DataFrame({'Class1':[87, 89],
                    'Class2':[85, 90]})
df2

Class1  Class2
0      87      85
1      89      90

In [137]:
df1.append(df2)

Class1  Class2
0      95      91
1      92      93
2      98      97
3     100      99
0      87      85
1      89      90

In [139]:
df1.append(df2, ignore_index=True)

Class1  Class2
0      95      91
1      92      93
2      98      97
3     100      99
4      87      85
5      89      90

In [141]:
df3 = pd.DataFrame({'Class1':[96,83]})
df3

Class1
0      96
1      83

In [143]:
df2.append(df3, ignore_index=True)

Class1  Class2
0      87    85.0
1      89    90.0
2      96     NaN
3      83     NaN

In [144]:
df_A_B = pd.DataFrame({'판매월': ['1월', '2월', '3월', '4월'],
                       '제품A': [100, 150, 200, 130],
                       '제품B': [90, 110, 140, 170]})
df_A_B

판매월  제품A  제품B
0  1월  100   90
1  2월  150  110
2  3월  200  140
3  4월  130  170

In [145]:
df_C_D = pd.DataFrame({'판매월': ['1월', '2월', '3월', '4월'],
                       '제품C': [112, 141, 203, 134],
                       '제품D': [90, 110, 140, 170]})
df_C_D

판매월  제품C  제품D
0  1월  112   90
1  2월  141  110
2  3월  203  140
3  4월  134  170

In [146]:
df_A_B.merge(df_C_D)

판매월  제품A  제품B  제품C  제품D
0  1월  100   90  112   90
1  2월  150  110  141  110
2  3월  200  140  203  140
3  4월  130  170  134  170

In [147]:
df_left = pd.DataFrame({'key':['A','B','C'], 'left':[1, 2, 3]})
df_left

key  left
0   A     1
1   B     2
2   C     3

In [148]:
df_right = pd.DataFrame({'key':['A','B','D'], 'right':[4, 5, 6]})
df_right

key  right
0   A      4
1   B      5
2   D      6

In [149]:
df_left.merge(df_right, how='left', on='key')

key  left  right
0   A     1    4.0
1   B     2    5.0
2   C     3    NaN

In [150]:
df_left.merge(df_right, how='right', on='key')

key  left  right
0   A   1.0      4
1   B   2.0      5
2   D   NaN      6

In [151]:
df_left.merge(df_right, how='outer', on='key')

key  left  right
0   A   1.0    4.0
1   B   2.0    5.0
2   C   3.0    NaN
3   D   NaN    6.0

In [152]:
df_left.merge(df_right, how='inner', on='key')

key  left  right
0   A     1      4
1   B     2      5

In [156]:
pd.read_csv('C:/Users/LGE1/TIL/python/IntroductionToPython/sea_rain1.csv', encoding='cp949')

연도       동해       남해       서해       전체
0  1996  17.4629  17.2288  14.4360  15.9067
1  1997  17.4116  17.4092  14.8248  16.1526
2  1998  17.5944  18.0110  15.2512  16.6044
3  1999  18.1495  18.3175  14.8979  16.6284
4  2000  17.9288  18.1766  15.0504  16.6178

In [157]:
# DataFrame -> txt파일로 저장

df_WH = pd.DataFrame({'Weight':[62, 67, 55, 74],
                      'Height':[165, 177, 160, 180]},
                       index = ['ID_1', 'ID_2', 'ID_3', 'ID_4'])
df_WH.index.name = 'User'
df_WH

Weight  Height
User                
ID_1      62     165
ID_2      67     177
ID_3      55     160
ID_4      74     180

In [158]:
bmi = df_WH['Weight']/(df_WH['Height']/100)**2
bmi

User
ID_1    22.773186
ID_2    21.385936
ID_3    21.484375
ID_4    22.839506
dtype: float64

In [159]:
df_WH['BMI'] = bmi
df_WH

Weight  Height        BMI
User                           
ID_1      62     165  22.773186
ID_2      67     177  21.385936
ID_3      55     160  21.484375
ID_4      74     180  22.839506

In [160]:
df_WH.to_csv('C:/Users/LGE1/TIL/python/IntroductionToPython/test_data.csv')

In [162]:
!type C:\Users\LGE1\TIL\python\IntroductionToPython\test_data.csv

User,Weight,Height,BMI
ID_1,62,165,22.77318640955005
ID_2,67,177,21.38593635289987
ID_3,55,160,21.484374999999996
ID_4,74,180,22.839506172839506


In [164]:
df_pr = pd.DataFrame({'판매가격':[2000, 3000, 5000, 10000],
                      '판매량':[32, 53, 40, 25]},
                     index=['P001', 'P002', 'P003', 'P004'])
df_pr.index.name = '제품번호'
df_pr

판매가격  판매량
제품번호            
P001   2000   32
P002   3000   53
P003   5000   40
P004  10000   25

In [165]:
df_pr.to_csv('C:/Users/LGE1/TIL/python/IntroductionToPython/dataframe_cp949.txt', sep=" ", encoding="cp949")

In [166]:
!type C:\Users\LGE1\TIL\python\IntroductionToPython\dataframe_cp949.txt

제품번호 판매가격 판매량
P001 2000 32
P002 3000 53
P003 5000 40
P004 10000 25
