In [3]:
# 백준 10815

n = int(input())
a = list(map(int, input().split()))

mini = 1000000
maxx = -1000000

for x in a:
    if mini > x :
        mini = x
    if maxx < x :
        maxx = x
        
print(mini, maxx)

5
20 10 35 30 7
7 35


In [10]:
# 백준 2577

a = int(input())
b = int(input())
c = int(input())

solve = list(map(int, str(a * b * c)))
ans = [0]*10

for i in solve:
    ans[i] += 1

print(*ans, sep='\n')

150
266
427
3
1
0
2
0
0
0
2
0
0


In [13]:
# 백준 3052

ans = [0] * 42

for _ in range(10):
    n = int(input())
    i = n % 42
    ans[i] = 1

print(sum(ans))

1
2
3
4
5
6
7
8
9
10
10


In [14]:
# 백준 2562

maxx = 0
maxid = 0

for i in range(1, 10):
    n = int(input())
    if maxx < n:
        maxx = n
        maxid = i
        
print(maxx)
print(maxid)

3
29
38
12
57
74
40
85
61
85
8


In [24]:
# 코드업 6095 (다차원 리스트)

# 19x19 리스트 필요

a = [ [0] * 19 for _ in range(19) ]
n = int(input())

for _ in range(n):
    i, j = map(int, input().split())
    a[i-1][j-1] = 1

for row in a:
    for col in row:
        print(col, end=' ')
    print()

5
1 1
2 2
3 3
4 4
5 5
1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 


In [51]:
# 코드업 6096 (다차원 리스트)

# 19x19 리스트를 입력

a = [ list(map(int, input().split())) for _ in range(19) ]

n = int(input())

for i in range(n):
    x, y = map(int, input().split())
    for j in range(19) :
        if a[j][y-1] == 0 :
            a[j][y-1] = 1
        else :
            a[j][y-1] = 0
            
        if a[x-1][j] == 0 :
            a[x-1][j] = 1
        else :
            a[x-1][j] = 0
    
for i in range(19):
    for j in range(19):
        print(a[i][j], end=' ')
    print()

0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0
2
10 10
12 12
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [ ]:
a = [
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,],
  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,],
  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,],


In [73]:
# 별 찍기-1
# 별을 리스트 내에서 표현

a = [[ '' for _ in range(5)] for _ in range(5)]

for i in range(5):
    for j in range(i+1): # range(0)이면 for문 동작x 따라서 +1 해야함
        a[i][j] = '*'
        
for i in range(5):
    for j in range(5):
        print(a[i][j], end='')
    print()

*
**
***
****
*****


In [72]:
n = 5
a = [ [''] * n for y in range(n)]

for i in range(n):
    for j in range(i+1):
       #print(f'a[{i}][{j}]')
        a[i][j] = '*'

for i in range(n):
    for j in range(n):
        print(a[i][j], end='')
    print()

*
**
***
****
*****


In [91]:
#별찍기 -2

n = 5
a = [ [' '] * n for y in range(n)]

for i in range(n):
    for j in range(i+1):
        a[i][n-j-1] = '*'

for i in range(n):
    for j in range(n):
        print(a[i][j], end='')
    print()

    *
   **
  ***
 ****
*****


In [92]:
# 별찍기 -3

n = 5
a = [ [''] * n for y in range(n)]

for i in range(n):
    for j in range(n-i):
        a[i][j] = '*'

for i in range(n):
    for j in range(n):
        print(a[i][j], end='')
    print()

*****
****
***
**
*


In [105]:
# 별찍기 -4

n = 5
a = [ [' '] * n for y in range(n)]

for i in range(n):
    for j in range(n-i):
        a[i][n-j-1] = '*'

for i in range(n):
    for j in range(n):
        print(a[i][j], end='')
    print()

*****
 ****
  ***
   **
    *


In [1]:
import numpy as np

In [3]:
arrN = np.arange(1, 31).reshape(3, 10)
arrN

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [5]:
arrN[1, 5]

16

In [6]:
arrN[2, -2]

29

In [8]:
arrN[1, 3:6]

array([14, 15, 16])

In [10]:
arrN[1:, -3]

array([18, 28])

In [12]:
arrN[:2, -2:]

array([[ 9, 10],
       [19, 20]])

In [13]:
arrn = np.arange(1, 51).reshape(5, 10)
arrn

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [14]:
arrn[1:4, 3:7]

array([[14, 15, 16, 17],
       [24, 25, 26, 27],
       [34, 35, 36, 37]])

In [15]:
arrn[1:4, 1]

array([12, 22, 32])

In [22]:
# 로또 번호 생성기


np.random.choice(np.arange(1, 46), size=6, replace=False)


array([29, 38, 16, 41, 18, 22])