## 학습목표
1. ndarray shape 변경하기

In [1]:
import numpy as np

**ravel, np.ravel**
- 다차원배열을 1차원으로 변경
- 'order' 파라미터
 - 'C' - row 우선 변경
 - 'F' - column 우선 변경

In [17]:
x = np.arange(15).reshape(3, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [19]:
np.ravel(x, order ='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
np.ravel(x, order='F')

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [10]:
temp = x.ravel()
print(temp)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [12]:
temp[0] = 15
print(temp)
print(x)

[15  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[15  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


**flatten**
- 다차원 배열을 1차원으로 변경
- ravel과의 차이점: copy를 생성하여 변경함(즉 원본데이터가 아닌 복사본을 반환)
- 'order' 파라미터
 - 'C' - row 우선 변경
 - 'F' - column 우선 변경

In [24]:
y = np.arange(16).reshape(4,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
y.flatten(order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [22]:
y.flatten(order='F')

array([ 0,  4,  8, 12,  1,  5,  9, 13,  2,  6, 10, 14,  3,  7, 11, 15])

In [21]:
t2 = y.flatten()
print(t2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [14]:
t2[0] = 16
print(t2)
print(y)

[16  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [25]:
x = np.arange(30).reshape(2, 3, 5)
print(x)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [26]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

**reshape 함수**
- array의 shape을 다른 차원으로 변경
- 주의할 점은 reshape한 후의 결과의 전체 원소의 개수와 이전 개수가 같아야 가능
- 예) 이미지 데이터 벡터화 - 이미지는 기본적으로 2차원 혹은 3차원(RGB)이나 트레이닝을 위해 1차원으로 변경하여 사용됨

In [28]:
x = np.arange(36)
print(x)
print(x.shape)
print(x.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
(36,)
1


In [29]:
x.reshape(6, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [30]:
x.reshape(6, -1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [31]:
x.reshape(-1, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [32]:
y = x.reshape(6, 6)
print(y.shape)
print(y.ndim)

(6, 6)
2


In [39]:
k = x.reshape(3, 3, -1)
print(k,'\n')
print(k.shape)
print(k.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]] 

(3, 3, 4)
3


## 학습목표
1. numpy에서 자주 사용되는 함수들을 사용해보기

In [40]:
import numpy as np

**numpy documentation**
- numpy 공식 문서 링크(https://numpy.org/devdocs/reference/)
- numpy에서 제공되는 함수 등에 대한 문서

In [41]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.91421518 0.66473501 0.43740378 0.44247387 0.34893612]
 [0.61876457 0.99640707 0.50638095 0.42407299 0.95441368]
 [0.3470079  0.91496944 0.17196977 0.18469454 0.18057343]]


**연산 함수**
- add, substract, multiply, divide

In [42]:
np.add(x, y)

array([[ 0.91421518,  1.66473501,  2.43740378,  3.44247387,  4.34893612],
       [ 5.61876457,  6.99640707,  7.50638095,  8.42407299,  9.95441368],
       [10.3470079 , 11.91496944, 12.17196977, 13.18469454, 14.18057343]])

In [43]:
np.subtract(x, y)

array([[-0.91421518,  0.33526499,  1.56259622,  2.55752613,  3.65106388],
       [ 4.38123543,  5.00359293,  6.49361905,  7.57592701,  8.04558632],
       [ 9.6529921 , 10.08503056, 11.82803023, 12.81530546, 13.81942657]])

In [44]:
np.multiply(x, y)

array([[ 0.        ,  0.66473501,  0.87480756,  1.32742162,  1.39574449],
       [ 3.09382284,  5.97844243,  3.54466663,  3.39258392,  8.58972312],
       [ 3.47007895, 10.06466379,  2.06363721,  2.40102897,  2.52802805]])

In [45]:
np.divide(x, y)

array([[ 0.        ,  1.50435886,  4.5724342 ,  6.78006133, 11.46341616],
       [ 8.08061784,  6.0216353 , 13.82358489, 18.86467703,  9.42987322],
       [28.81778812, 12.02225952, 69.77970716, 70.38648922, 77.53078543]])

In [46]:
x + y

array([[ 0.91421518,  1.66473501,  2.43740378,  3.44247387,  4.34893612],
       [ 5.61876457,  6.99640707,  7.50638095,  8.42407299,  9.95441368],
       [10.3470079 , 11.91496944, 12.17196977, 13.18469454, 14.18057343]])

In [48]:
x - y

array([[-0.91421518,  0.33526499,  1.56259622,  2.55752613,  3.65106388],
       [ 4.38123543,  5.00359293,  6.49361905,  7.57592701,  8.04558632],
       [ 9.6529921 , 10.08503056, 11.82803023, 12.81530546, 13.81942657]])

In [49]:
x * y

array([[ 0.        ,  0.66473501,  0.87480756,  1.32742162,  1.39574449],
       [ 3.09382284,  5.97844243,  3.54466663,  3.39258392,  8.58972312],
       [ 3.47007895, 10.06466379,  2.06363721,  2.40102897,  2.52802805]])

In [50]:
x / y

array([[ 0.        ,  1.50435886,  4.5724342 ,  6.78006133, 11.46341616],
       [ 8.08061784,  6.0216353 , 13.82358489, 18.86467703,  9.42987322],
       [28.81778812, 12.02225952, 69.77970716, 70.38648922, 77.53078543]])

**통계 함수**
- 평균,분산,중앙,최대,최소값 등등 통계 관련된 함수가 내장

In [51]:
print(y)

[[0.91421518 0.66473501 0.43740378 0.44247387 0.34893612]
 [0.61876457 0.99640707 0.50638095 0.42407299 0.95441368]
 [0.3470079  0.91496944 0.17196977 0.18469454 0.18057343]]


In [52]:
np.mean(y)

0.5404678855637255

In [53]:
y.mean()

0.5404678855637255

In [54]:
np.max(y)

0.996407072023395

In [56]:
np.argmax(y) #최대값의 인덱스

6

In [57]:
np.var(y), np.median(y), np.std(y)

(0.07877855110739197, 0.4424738736383661, 0.28067517009417126)

**집계함수**
- 합계(sum), 누적합계(cumsum)등 계산 가능

In [58]:
y

array([[0.91421518, 0.66473501, 0.43740378, 0.44247387, 0.34893612],
       [0.61876457, 0.99640707, 0.50638095, 0.42407299, 0.95441368],
       [0.3470079 , 0.91496944, 0.17196977, 0.18469454, 0.18057343]])

In [61]:
np.sum(y)

8.107018283455883

In [62]:
np.cumsum(y)

array([0.91421518, 1.57895018, 2.01635396, 2.45882784, 2.80776396,
       3.42652853, 4.4229356 , 4.92931655, 5.35338954, 6.30780322,
       6.65481111, 7.56978055, 7.74175032, 7.92644485, 8.10701828])

**any, all 함수**
- any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
- all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [63]:
z = np.random.randn(10)
print(z)

[-0.78371056  0.1884264  -0.86765059 -0.51128314  0.36413241 -1.35131002
 -0.41491223 -1.46345543  0.67488294  0.13592902]


In [66]:
z > 0

array([False,  True, False, False,  True, False, False, False,  True,
        True])

In [65]:
np.any(z > 0)

True

In [67]:
np.all(z > 0)

False

In [68]:
np.all(z != 0)

True

**where 함수**
- 조건에 따라 선별적으로 값을 선택 가능
- 예) 음수인 경우는 0, 나머지는 그대로 값을 쓰는 경우

In [70]:
z = np.random.randn(10)
print(z)

[ 1.57165675  0.42318706  0.12123994  1.31693809 -0.88926262 -1.74463728
  0.01839459 -0.93168776  0.82731111  0.13955141]


In [71]:
np.where(z > 0, z, 0) # *.where(조건,참인 경우,거짓인 경우)

array([1.57165675, 0.42318706, 0.12123994, 1.31693809, 0.        ,
       0.        , 0.01839459, 0.        , 0.82731111, 0.13955141])